### ISSUE TITLE
some errors 

### ISSUE THREAD

**Issue by mashrura011** [SaltyOrange/SimpleTrafficLightDetection#1]
hi, 
would you please help me with some error fixing? i downloaded your code and tried running but there were these errors i could not fix since i am new at this and i have this huge project due. this would be a great help.
<img width="960" alt="error" src="https://cloud.githubusercontent.com/assets/26203123/23589029/87c13efc-01f0-11e7-9e0a-30f13f78af25.png">

**Comment by SaltyOrange** [comment]
Unfortunately, the code isn't Python 2/3 compatible. I used Python 3 for the version on GitHub, but you can change that line with `self.templates = list(self.initial_templates)` and it should work.

**Comment by mashrura011** [comment]
<img width="960" alt="2" src="https://cloud.githubusercontent.com/assets/26203123/23589624/8c94232c-01fa-11e7-92b3-8005cd88d82a.png">
hey thankyou soo much!! but i am really really new at this and i am badly
in need of doing this! this would be very kind of you if you could tell me
whats wrong now?
